# Math operations in TensorFlow

We will explore some of the math operations in Tensorflow using Eager execution mode. 

In [1]:
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf

Define x and y:

In [2]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

In [4]:
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 2., 1.], dtype=float32)>

## Basic Operations

#### Addition

In [5]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

#### Subtraction

In [6]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

#### Multiplication

In [7]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

In [11]:
arr = np.array([1, 2, 3])

NameError: name 'np' is not defined

#### Division

In [6]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

#### Square

In [8]:
x.numpy()

array([1., 2., 3.], dtype=float32)

In [9]:
square = tf.square(x)
square.numpy()

array([1., 4., 9.], dtype=float32)

#### Dot Product

In [13]:
x.numpy()

array([1., 2., 3.], dtype=float32)

In [14]:
y.numpy()

array([3., 2., 1.], dtype=float32)

In [12]:
dot_product = tf.reduce_sum(tf.multiply(x, y))

dot_product.numpy()

10.0

## Finding the index of min and max element

In [18]:
x = tf.constant([10, 0, 13, 9, 100, 299, -12.5])

Index of minimum value:

In [28]:
index_min = tf.argmax(x).numpy()
x.numpy()[index_min]


299.0

In [22]:
tf.math.minimum(x)

TypeError: minimum() missing 1 required positional argument: 'y'

Index of maximum value:

In [17]:
tf.argmax(x).numpy()

5

### Squared Difference 

In [33]:
x = tf.Variable([1, 3, 5, 7, 11])
y = tf.Variable([1, 1, 1, 1, 1])

tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100])

### Power

x^x

In [41]:
x = tf.Variable([1,2,3,4])
result = tf.pow(x, 2).numpy()
result


InvalidArgumentError: Integers to negative integer powers are not allowed [Op:Pow]

## Rank of the matrix

In [42]:
x = tf.constant([[[1,2,4],[3,4,5]],
             [[1,2,4],[3,4,5]]])

x.shape

TensorShape([2, 2, 3])

In [17]:
x.numpy()

array([[[1, 2, 4],
        [3, 4, 5]],

       [[1, 2, 4],
        [3, 4, 5]]])

## Reshape the matrix

In [43]:
x = tf.constant([[1,2,3,4], [5,6,7,8]])

In [44]:
x.shape

TensorShape([2, 4])

In [45]:
x.numpy()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
tf.reshape(x,[2,2,2]).numpy()

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Transpose the matrix

In [48]:
x.numpy()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
tf.transpose(x)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

In [51]:
import numpy as np

three_d_arr = np.random.rand(3,3,3)


In [52]:
three_d_arr

array([[[0.45384543, 0.60853657, 0.95702797],
        [0.8410302 , 0.93087297, 0.97744458],
        [0.95508107, 0.44313821, 0.69284716]],

       [[0.94716334, 0.04589093, 0.06917602],
        [0.69604374, 0.38092227, 0.6338999 ],
        [0.25614196, 0.83367001, 0.93002463]],

       [[0.42533046, 0.04944764, 0.46042035],
        [0.78864306, 0.41709562, 0.53889202],
        [0.28489563, 0.92267168, 0.89761143]]])

In [53]:
my_tensor = tf.Variable(three_d_arr)

In [54]:
my_tensor

<tf.Variable 'Variable:0' shape=(3, 3, 3) dtype=float64, numpy=
array([[[0.45384543, 0.60853657, 0.95702797],
        [0.8410302 , 0.93087297, 0.97744458],
        [0.95508107, 0.44313821, 0.69284716]],

       [[0.94716334, 0.04589093, 0.06917602],
        [0.69604374, 0.38092227, 0.6338999 ],
        [0.25614196, 0.83367001, 0.93002463]],

       [[0.42533046, 0.04944764, 0.46042035],
        [0.78864306, 0.41709562, 0.53889202],
        [0.28489563, 0.92267168, 0.89761143]]])>

In [55]:
tf.transpose(my_tensor, perm=[0, 2, 1])

<tf.Tensor: shape=(3, 3, 3), dtype=float64, numpy=
array([[[0.45384543, 0.8410302 , 0.95508107],
        [0.60853657, 0.93087297, 0.44313821],
        [0.95702797, 0.97744458, 0.69284716]],

       [[0.94716334, 0.69604374, 0.25614196],
        [0.04589093, 0.38092227, 0.83367001],
        [0.06917602, 0.6338999 , 0.93002463]],

       [[0.42533046, 0.78864306, 0.28489563],
        [0.04944764, 0.41709562, 0.92267168],
        [0.46042035, 0.53889202, 0.89761143]]])>

## Typecasting 

In [66]:
a = x.numpy()
a[1] = 4.44444
print(a)
t = tf.Variable(a)
t = tf.cast(t, dtype=tf.int16)
t.numpy()

[[1.      2.      3.      4.     ]
 [4.44444 4.44444 4.44444 4.44444]]


array([[1, 2, 3, 4],
       [4, 4, 4, 4]], dtype=int16)

In [58]:
x.dtype

tf.int32

In [60]:
x = tf.cast(x, dtype=tf.float32)

x.dtype

tf.float32

In [61]:
x.numpy()

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

## Concatenating two matrices

In [67]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

In [69]:
x

[[3, 6, 9], [7, 7, 7]]

Concatenate row-wise:

In [68]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]])

Concatenate column-wise:

In [25]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]])

Stack x matrix:

In [71]:
x

[[3, 6, 9], [7, 7, 7]]

In [73]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]])

## Reduce Mean

In [74]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])

In [75]:
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Compute average values i.e (1.0 + 5.0 + 2.0 + 3.0) / 4

In [76]:
tf.reduce_mean(x).numpy() 

2.75

Average across the row i.e, [ (1.0+2.0)/2, (5.0+3.0)/2]

In [77]:
tf.reduce_mean(input_tensor=x, axis=0).numpy() 

array([1.5, 4. ], dtype=float32)

Average across the column i.e [(1.0+5.0)/2.0, (2.0+3.0)/2.0]

In [78]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

## Reduce Sum

In [79]:
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Sum values across the rows i.e  [(1.0+2.0),(5.0 + 3.0)]

In [80]:
tf.reduce_sum(x, 0).numpy()

array([3., 8.], dtype=float32)

Sum values across the columns i.e  [(1.0+5.0),(2.0 + 3.0)]

In [81]:
tf.reduce_sum(x, 1).numpy()

array([6., 5.], dtype=float32)

Sum all the values i.e 1.0 + 5.0 + 2.0 + 3.0

In [82]:
tf.reduce_sum(x, [0, 1]).numpy()

11.0

## Drawing Random values

Drawing values from the normal distribution:

In [88]:
tf.random.normal(shape=(3,2), mean=50.0, stddev=1.0).numpy()

array([[51.776657, 73.57122 ],
       [60.372036, 36.341515],
       [43.43262 , 71.89406 ]], dtype=float32)

Drawing values from the uniform distribution:

In [92]:
tf.random.uniform(shape = (3,2),  minval=-10, maxval=10, dtype=tf.float32,).numpy()

array([[ 5.9752464,  3.3874273],
       [-4.487784 , -9.528006 ],
       [-8.685384 ,  6.073763 ]], dtype=float32)

## Create 0's and 1's

In [94]:
y = tf.zeros([5,5]).numpy()

In [93]:
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 5.],
       [2., 3.]], dtype=float32)>

In [95]:
tf.zeros_like(y).numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [40]:
tf.ones([5,5]).numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [96]:
tf.ones_like(y).numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

## Compute Softmax Probabilities

In [42]:
x = tf.constant([7., 2., 5.])

tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

## Create Indentity matrix

In [44]:
i_matrix = tf.eye(7)
print(i_matrix.numpy())

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


## L2 Normalization

In [45]:
tf.math.l2_normalize(x,axis=None, epsilon=1e-12,).numpy()

array([0.79259396, 0.22645542, 0.56613857], dtype=float32)

## Gradient Computation

In [47]:
def square(x):
  return tf.multiply(x, x)

with tf.GradientTape(persistent=True) as tape:
     print(square(6.).numpy())


36.0
